definitions:
  mgp.PaginateData-array_model_Audit:
    properties:
      items:
        items:
          items:
            $ref: '#/definitions/model.Audit'
          type: array
        type: array
      page:
        type: integer
      page_size:
        type: integer
      total:
        type: integer
    type: object
  mgp.Result-mgp_PaginateData-array_model_Audit:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/mgp.PaginateData-array_model_Audit'
        description: 返回数据/错误详细信息
      msg:
        description: 请求结果
        type: string
    type: object
  mgp.Result-model_Audit:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        allOf:
        - $ref: '#/definitions/model.Audit'
        description: 返回数据/错误详细信息
      msg:
        description: 请求结果
        type: string
    type: object
  model.Audit:
    properties:
      content:
        items:
          type: integer
        type: array
      created_at:
        type: string
      failed_reason:
        type: string
      id:
        type: integer
      new_data:
        items:
          type: integer
        type: array
      operation:
        type: string
      original_data:
        items:
          type: integer
        type: array
      status:
        $ref: '#/definitions/model.AuditStatus'
      updated_at:
        type: string
      username:
        type: string
    type: object
  model.AuditStatus:
    enum:
    - success
    - failed
    - running
    type: string
    x-enum-varnames:
    - AuditSuccess
    - AuditFailed
    - AuditRunning
  url.Values:
    additionalProperties:
      items:
        type: string
      type: array
    type: object
info:
  contact: {}
  title: My Gin Plus Example API
  version: "2.0"
paths:
  /:
    get:
      responses:
        "200":
          description: OK
  /{pk}:
    get:
      parameters:
      - in: path
        name: pk
        required: true
        type: integer
      responses:
        "200":
          description: OK
  /api/audit:
    get:
      parameters:
      - in: query
        name: order
        type: string
      - in: query
        name: page
        type: integer
      - in: query
        name: page_size
        type: integer
      - in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mgp.Result-mgp_PaginateData-array_model_Audit'
      security:
      - ApiKeyAuth: []
      summary: 分页获取审计记录
      tags:
      - 审计记录
  /api/audit/{pk}:
    get:
      parameters:
      - in: path
        name: pk
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mgp.Result-model_Audit'
      security:
      - ApiKeyAuth: []
      summary: 获取指定ID的审计记录
      tags:
      - 审计记录
schemes:
- https
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
